apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
spec:
  releaseName: flux
  chart:
    repository: https://charts.fluxcd.io/
    name: flux
    version: 1.2.0
  values:
    allowedNamespaces: []
    priorityClassName: "system-cluster-critical"

    sync:
      interval: "2m"

    git:
      url: "git@github.com:duyetdev/fluxd.git"
      branch: "master"
      path: "environments/dev"
      label: fluxcd-dev
      pollInterval: "2m"
      timeout: "5m"
      secretName: "flux-ssh"

      user: "FluxCD"
      email: "support@weave.works"

    registry:
      # Period at which to check for updated images
      automationInterval: "1m"
      # Maximum registry requests per second per host
      rps: 20
      # Maximum number of warmer connections to remote and memcache
      burst: 125

      prometheus:
        enabled: true
        serviceMonitor:
          create: true

    additionalArgs:
      - --connect=ws://fluxcloud

    resources:
      requests:
        cpu: 100m
        memory: 2000Mi
      limits:
        cpu: 200m
        memory: 2000Mi