apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
spec:
  releaseName: helm-operator
  chart:
    repository: https://charts.fluxcd.io/
    name: helm-operator
  values:
    createCRD: false
    chartsSyncInterval: 1m
    statusUpdateInterval: 30s

    git:
      pollInterval: 1m
      ssh:
        secretName: flux-ssh
    helm:
      versions: v3

    resources:
      requests:
        cpu: 100m
        memory: 600Mi
      limits:
        cpu: 200m
        memory: 600Mi