---
apiVersion: "helm.fluxcd.io/v1"
kind: "HelmRelease"
metadata:
  name: insights
  namespace: data
  annotations:
    fluxcd.io/automated: "true" 
    filter.fluxcd.io/: "glob:*"
spec:
  releaseName: insights
  forceUpgrade: true
  resetValues: true
  chart:
    repository: "https://charts.bitnami.com/bitnami"
    name: "bitnami/ghost"
  values:
    image:
      registry: docker.io
      repository: duyetdev/ghost
      tag: "3.15.3"
    ghostUsername: admin
    ghostPassword: admin

    persistence:
      enabled: true

    mariadb:
      enabled: true
      replication:
        enabled: true
      db:
        name: insights
        user: insights
      rootUser:
        password: insights

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
