apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
spec:
  releaseName: flux
  chart:
    repository: https://charts.fluxcd.io/
    name: flux
    version: 1.2.0
  values:
    allowedNamespaces: ["flux"]
    priorityClassName: "system-cluster-critical"

    sync:
      interval: 1m

    git:
      url: "git@github.com:duyetdev/fluxd"
      branch: "master"
      path: "environments/dev"
      label: flux-dev
      pollInterval: 1m
      timeout: "5m"
      secretName: "flux-ssh"

      user: "Stg FluxCD"
      email: "support@weave.works"

    resources:
      requests:
        cpu: 50m
        memory: 100Mi