git:
  url: "git@github.com:duyetdev/fluxd"
  branch: "master"
  path: "environments/dev"
  secretName: flux-ssh
registry:
  automationInterval: "1m"

allowedNamespaces: ["flux"]

resources:
  requests:
    cpu: 50m
    memory: 100Mi